services:
  postgres:
    image: postgres:18
    container_name: userdetails-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  api:
    build: ./UserDetailsApi
    container_name: userdetails-api
    ports:
      - "5066:5066"
    environment:
      ASPNETCORE_URLS: http://+:5066
      ConnectionStrings__UserDetailsDb: ${DB_CONNECTION}
      JwtSettings__Token: ${JWT_TOKEN}
      SMTP__Username: ${SMTP_USERNAME}
      SMTP__Password: ${SMTP_PASSWORD}

    depends_on:
      - postgres

  ui:
    build: ./UserDetailsFrontend
    container_name: userdetails-ui
    ports:
      - "4200:80"
    depends_on:
      - api

volumes:
  pgdata: